---
functional:
  - Пользователь может зарегистрироваться в ЛК
  - Пользователь может авторизоваться через email
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может выйти из ЛК
  - Пользователь может редактировать свой профиль
  - Пользователь может создавать новую игру
  - Пользователь может создавать новую игру без регистрации
  - Пользователь может менять язык програмирования в игре
  - Пользователь может писать в чат игры
  - Пользователь может играть с другим игроком
  - Пользователь может иргать с ботом
  - Пользователь может сдаться в игре
  - Пользователь может сбросить редактор кода в игре
  - Пользователь может менять язык текста
  - Пользователь может просматривать профиль других игроков
  - Пользователь может учавствовать в уже созданной игре
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6
