---
functional:
  - Пользователь может зарегистрироваться на сайте
  - Поле Nickname должно содержать от 3-16 символов
  - Поле Email должно быть валидным к форме (содержать @ и домен)
  - Поле Password должно содержать от 6-16 символов
  - Поле Password Confirmation должно совпадать с полем Password
  - Пользователь может авторизоваться через email
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может выйти из ЛК
  - Пользователь может редактировать свой профиль
  - Пользователь может создавать новую игру
  - Пользователь может создавать новую игру без регистрации
  - При создании новой игры можно выбирать различные параметры и время
  - В поле timeout во время игры должно отображаться время до завершения игры
  - Пользователь может менять язык програмирования в игре
  - Пользователь может писать в чат игры
  - Пользователь может играть с другим игроком
  - Пользователь может иргать с ботом
  - Пользователь может сдаться в игре
  - Пользователь может сбросить редактор кода в игре
  - Пользователь может менять язык текста
  - Пользователь может просматривать профиль других игроков
  - пользователь может просматривать завершенные игры и турниры
  - Пользователь может учавствовать в турнирах
  - Пользователь может учавствовать в уже созданной игре
  - Пользователь может менять тему сайта на темную и светлую
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен поддерживать несколько языков интерфейса (Русский, Английский)
  - При введении некорректных данных в форме регистрация должно появляться сообщение об ошибке
  - Пользователь не может писать код в поле другого участника
  - Возможность восстановить пароль через email
